function [Citation,VarName3,VarName7,VarName11] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [CITATION,VARNAME3,VARNAME7,VARNAME11] = IMPORTFILE(FILENAME) Reads
%   data from text file FILENAME for the default selection.
%
%   [CITATION,VARNAME3,VARNAME7,VARNAME11] = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   [Citation,VarName3,VarName7,VarName11] = importfile('CAB_radiation_2015-01.tab',41, 44680);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/10/26 00:25:36

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 41;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{yyyy-MM-dd'T'HH:mm}D)
%	column3: double (%f)
%   column7: double (%f)
%	column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{yyyy-MM-dd''T''HH:mm}D%*s%f%*s%*s%*s%f%*s%*s%*s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,0.0,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,0.0,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Citation = dataArray{:, 1};
VarName3 = dataArray{:, 2};
VarName7 = dataArray{:, 3};
VarName11 = dataArray{:, 4};

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% Citation=datenum(Citation);


